clientes/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static 

app_name = "clientes_app"

urlpatterns = [
    path('', views.Inicio.as_view(), name='inicio'),
    path('nosotros', views.Nosotros.as_view(), name='nosotros'),
    path('lista', views.Lista.as_view(), name='lista'),
    path('clientes/add', views.Crear.as_view(), name='crear'),
    path('clientes/editar/<pk>', views.Editar.as_view(), name='editar'),
    path('clientes/eliminar/<pk>', views.Eliminar.as_view(), name='eliminar'),
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

crud_clientes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clientes.urls')),
]

clientes/models.py
from django.db import models

# Create your models here.
class Lenguaje(models.Model):
    nom_len = models.CharField(max_length=100,verbose_name="Lenguaje")
    
    def __str__(self):
        fila = self.nom_len
        return fila
    
class SO(models.Model):
    nom_so = models.CharField(max_length=100,verbose_name="Sistema Operativo")
    
    def __str__(self):
        fila = self.nom_so
        return fila
    
Area = (
    ('Front','Front'),
    ('Backend','Backend'),
    ('FullStack','FullStack'),
)

class Cliente(models.Model):
    nom = models.CharField(max_length=50,verbose_name="Nombre")
    ap = models.CharField(max_length=50,verbose_name="Apellido Paterno")
    am = models.CharField(max_length=50,verbose_name="Apellido Materno")
    foto = models.ImageField(upload_to='imagenes/', verbose_name='Foto',null=True)
    lenguaje = models.ForeignKey(Lenguaje, verbose_name="Lenguaje", on_delete=models.CASCADE)
    so = models.ForeignKey(SO, verbose_name="Sistema Operativo", on_delete=models.CASCADE)
    area = models.CharField(max_length=50,verbose_name="Area", choices=Area)
    
    def __str__(self):
            fila = "ID: " + str(self.id) + " - " + self.nom + " " + self.ap + " " + self.am
            return fila 
    
    def delete(self, using=None, Keep_parents=False):
        self.foto.storage.delete(self.foto.name)
        super().delete()

clientes/forms.py
from dataclasses import fields
from socket import fromshare
from django import forms 
from .models import Cliente


class ClientesForm(forms.ModelForm):
    class Meta:
        model=Cliente
        fields='__all__'
        
    def __init__(self, *args, **kwargs):
        super(ClientesForm,self).__init__(*args,**kwargs)
        self.fields['lenguaje'].empty_label="Selecciona"
        self.fields['so'].empty_label="Selecciona"
        self.fields['area'].empty_label="Selecciona"
        self.fields["area"].choices = [("", "Selecciona"),]+ list(self.fields["area"].choices)[1:]
        self.fields['ap'].required=True
        self.fields['am'].required=False
        

clientes/views.py
from django.shortcuts import render
from .models import *
from .forms import ClientesForm
from django.views.generic import TemplateView,CreateView,ListView,UpdateView,DeleteView
from django.urls import reverse_lazy, reverse

# Create your views here.
class Inicio(TemplateView):
    template_name = 'paginas_base/inicio.html'
    
class Nosotros(TemplateView):
    template_name = 'paginas_base/nosotros.html'
    
class Lista(ListView):
    template_name = 'crud/lista.html'
    model = Cliente
    ordering = 'nom'
    queryset = Cliente.objects.all()
    context_object_name = 'clientes'
    
class Crear(CreateView):
    template_name = 'crud/crear.html'
    model = Cliente
    form_class = ClientesForm
    
    def get_success_url(self, **kwargs):
        return reverse("clientes_app:lista")
    
class Editar(UpdateView):
    template_name = 'crud/editar.html'
    model = Cliente
    form_class = ClientesForm
    pk_url_kwarg = 'pk'
    
    def get_success_url(self, **kwargs):
        return reverse("clientes_app:lista")
    
class Eliminar(DeleteView):
    template_name = 'crud/eliminar.html'
    model = Cliente
    pk_url_kwarg = 'pk'
    
    def get_success_url(self, **kwargs):
        return reverse("clientes_app:lista")

clientes/templates/Crud/Eliminar.html
{% extends 'paginas_base/base.html' %}
{% block titulo %}Página Eliminar {% endblock titulo %}

{% block contenido %}
<h1>Eliminar Cliente {{ object.nom }}</h1>
<form method="post" id="fr_eliminar"> {% csrf_token %}
    <p>¿Está seguro que desea eliminar?</p>
    <button type="submit" class="btn btn-danger">Confirmar</button>
</form> 
<a name="" id="bteleminar" class="btn btn-primary btnEliminar" href="{% url 'clientes_app:lista' %}" role="button">Cancelar</a>
{% endblock contenido %} 

clientes/templates/Crud/crear.html
{% extends 'paginas_base/base.html' %}
{% load crispy_forms_tags %}

{% block titulo %}Página Nuevo Cliente {% endblock titulo %}
{% block contenido %}  
<div class="card">
    <div class="card-header">Crear Nuevo Cliente</div>
        <div class="card-body">
            <h4 class="card-title">Nuevo Cliente</h4>
            <form action="" method="post"  enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                {% comment %} {{ form|crispy}} {% endcomment %}
                {{form.nom|as_crispy_field}} <br>
                {{form.ap|as_crispy_field}} <br>
                {{form.am|as_crispy_field}} <br>

                {% if form.foto.value %}
                <img src="{{MEDIA_URL}}/imagenes/{{formulario.foto.value}}" alt="" width="80">
                {% endif %}
                {{form.foto|as_crispy_field}}
                <br>
                {{form.lenguaje|as_crispy_field}}
                <br>
                {{form.so|as_crispy_field}}
                <br>
                {{form.area|as_crispy_field}}
                <br>
                <input name="btn-guardar" id="btn_guardar" class="btn btn-success" type="submit" value="Guardar">
                <a name="btnCancelar" id="btnCancelar" class="btn btn-primary" href="{% url 'clientes_app:lista' %}" role="button">Cancelar</a>
            </form>      
        </div>
    </div>
</div>
{% endblock contenido %}

clientes/templates/Crud/editar.html
{% extends 'paginas_base/base.html' %}
{% load crispy_forms_tags %}

{% block titulo %}Página Editar Cliente {% endblock titulo %}
{% block contenido %}
<div class="card">
    <div class="card-header">Crear Nuevo Cliente</div>
        <div class="card-body">
            <h4 class="card-title">Nuevo Cliente</h4>
            <form action="" method="post"  enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                {% comment %} {{ form|crispy}} {% endcomment %}
                {{form.nom|as_crispy_field}} <br>
                {{form.ap|as_crispy_field}} <br>
                {{form.am|as_crispy_field}} <br>

                {% if form.foto.value %}
                <img src="{{MEDIA_URL}}/imagenes/{{formulario.foto.value}}" alt="" width="80">
                {% endif %}
                {{form.foto|as_crispy_field}}
                <br>
                {{form.lenguaje|as_crispy_field}}
                <br>
                {{form.so|as_crispy_field}}
                <br>
                {{form.area|as_crispy_field}}
                <br>
                <input name="btn-guardar" id="btn_guardar" class="btn btn-success" type="submit" value="Guardar">
                <a name="btnCancelar" id="btnCancelar" class="btn btn-primary" href="{% url 'clientes_app:lista' %}" role="button">Cancelar</a>
            </form>      
        </div>
    </div>
</div>
{% endblock contenido %}

clientes/templates/Crud/form.html
<form enctype="multipart/form-data" method="POST">
{% csrf_token %}


<input name="btn-guardar" id="btn_guardar" class="btn btn-success" type="submit" value="Guardar">
<a name="btnCancelar" id="btnCancelar" class="btn btn-primary" href="#" role="button">Cancelar</a>

</form>

clientes/templates/Crud/lista.html
{% extends 'paginas_base/base.html' %}

{% block titulo %}Página Lista de Clientes {% endblock titulo %}
{% block contenido %}
    <div class="card">
        <div class="card-header">
            <a name="btnuevo" id="btnuevo" class="btn btn-primary" href="{% url 'clientes_app:crear' %}" role="button">Agregar Cliente</a>
        </div>
        <div class="card-body">
            <h4 class="card-title">Clientes</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                        <th>Apellido Paterno</th>
                        <th>Apellido Materno</th>                       
                        <th>Lenguaje</th>
                        <th>Sistema Operativo</th>
                        <th>Area</th>
                        <th>Foto</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {%  for cl in clientes %}
                    <tr>
                        <td>{{ cl.id }}</td>
                        <td>{{ cl.nom }}</td>
                        <td>{{ cl.ap }}</td>
                        <td>{{ cl.am }}</td>
                        <td>{{ cl.lenguaje }}</td>
                        <td>{{ cl.so }}</td>
                        <td>{{ cl.area }}</td>
                        <td>
                            <img src="{{ cl.foto.url }}" height="60">
                        </td>
                        <td>
                            <a name="bteditar" id="bteditar" class="btn btn-info" href="{% url 'clientes_app:editar' cl.id %}" role="button">Editar</a>
                            <a name="bteliminar" id="bteliminar" class="btn btn-danger" href="{% url 'clientes_app:eliminar' cl.id %}" role="button">Eliminar</a>
                        </td>                        
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
            
            
        </div>
        <div class="card-footer text-muted">
        
        </div>
    </div>
   
   

{% endblock contenido %}

clientes/templates/paginas_base/base.html
{% load static  %}
<!doctype html>
<html lang="en">
    <head>
        <title>
        {% block titulo %}
            
        {% endblock titulo %}
            </title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
        <link rel="stylesheet" type="text/css" href="{% static 'estilos.css' %}" >
    </head>

    <body>
        <!-- Menu de Navegacion -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'clientes_app:inicio' %}">CRUD Clientes</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'clientes_app:inicio' %}">Inicio</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'clientes_app:nosotros' %}">Nosotros</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'clientes_app:lista' %}">Clientes</a>
                  </li>
                </ul>
              </div>
            </div>
        </nav>

        <div class="container">
            <div class="row">
                <div class="col-12">
                    <br>
                    {% block contenido %}{% endblock contenido %}
                </div>
            </div>
        </div>
       

        <header>
            <!-- place navbar here -->
        </header>
        <main></main>
        <footer>
            <!-- place footer here -->
        </footer>
        <!-- Bootstrap JavaScript Libraries -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

clientes/templates/paginas_base/inicio.html
{% extends 'paginas_base/base.html' %}

{% block titulo %}Página de Inicio {% endblock titulo %}
{% block contenido %}
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Bienvenidos al Sistema de Clientes #03</h1>
        <p class="col-md-8 fs-4">Esto es un CRUD de la seccion de clientes</p>
        <a  href="{% url 'clientes_app:lista' %}">
            <button class="btn btn-primary btn-lg" type="button">Listado de Clientes</button>
        </a>
        </div>
    </div>

{% endblock contenido %}

clientes/templates/paginas_base/nosotros.html
{% extends 'paginas_base/base.html' %}

{% block titulo %}Página Nosotros {% endblock titulo %}
{% block contenido %}
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
        <h1 class="display-4 fst-italic">Title of a longer featured blog post</h1>
        <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
        <p class="lead mb-0"><a href="#" class="text-white fw-bold">Continue reading...</a></p>
        </div>
    </div>

    <div class="row mb-2">
        <div class="col-md-6">
          <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
              <strong class="d-inline-block mb-2 text-primary">World</strong>
              <h3 class="mb-0">Featured post</h3>
              <div class="mb-1 text-muted">Nov 12</div>
              <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
              <a href="#" class="stretched-link">Continue reading</a>
            </div>
            <div class="col-auto d-none d-lg-block">
              <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
    
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
              <strong class="d-inline-block mb-2 text-success">Design</strong>
              <h3 class="mb-0">Post title</h3>
              <div class="mb-1 text-muted">Nov 11</div>
              <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
              <a href="#" class="stretched-link">Continue reading</a>
            </div>
            <div class="col-auto d-none d-lg-block">
              <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
    
            </div>
          </div>
        </div>
      </div>
   

{% endblock contenido %}